[package]
name = "tsp_machine"
version = "0.1.0"
authors = ["Ricardo M. Biot"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"

[profile.release]
opt-level = 3